### ISSUE TITLE
unwanted > sign seen in contact.html

### ISSUE THREAD

**Issue by rajmohanpdy** [kelvinconrad/fuse-Blog#1]
in contact.html noticed some unwanted > sign which is irrelevant to the content. 
<img width="300" alt="unwanted_sign" src="https://user-images.githubusercontent.com/7533607/98445075-a336d980-213b-11eb-82ad-1455f90c8143.PNG">

**Comment by kelvinconrad** [comment]
Ohh let me fix that

**Comment by kelvinconrad** [comment]
> Ohh let me fix that

its fixed already
